name: Veracode Container Scanning

on:
  push:
jobs:
  container_scanning: 
    name: Container Security
    runs-on: ubuntu-latest
    steps: 
      - name: Check out branch
        uses: actions/checkout@v2
  
      - name: Container Security  
        run: |
            pwd
            export VERACODE_API_KEY_ID=${{ secrets.VERACODE_API_ID }}
            export VERACODE_API_KEY_SECRET=${{ secrets.VERACODE_API_KEY }}
            curl -fsS https://tools.veracode.com/veracode-cli/install | sh
            ./veracode package --source . -o . -a 
           
